services:
    app:
        build: ./app
        ports:
            - "8080:8080"
        volumes:
            - ./app/src:/root/app
        tty: true
        restart: always
    nginx:
        restart: always
        image: nginx:latest
        container_name: nginx
        ports:
            - "8443:80"
        volumes:
            # NGINXのコンフィグファイルをホストOSから、ゲストOSに連結する
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/keys:/etc/nginx/keys
            - ./nginx/statics:/etc/nginx/static/statics
        tty: true
